### ISSUE TITLE
stupid question : color format

### ISSUE THREAD

**Issue by amapic** [winkerVSbecks/3d-particle-effects-demo#1]
Hi, thanks for transmitting your work.
What is the format of color you use in Sparks ? 
https://github.com/winkerVSbecks/3d-particle-effects-demo/blob/main/src/Sparks.js
And what does this line do ?
colors[parseInt(colors.length * Math.random(), 10)], (line 55)
Thank you

**Comment by winkerVSbecks** [comment]
That line just picks a random value from the colors array 

Just hex, the list of colors is defined here. https://github.com/winkerVSbecks/3d-particle-effects-demo/blob/94ce30f77c759b521d786ae13481a870806a02e4/src/Scene.js#L8
